name: notus_format
description: Platform-agnostic rich text document model based on Delta format and used in Zefyrka editor.
version: 1.0.1
homepage: https://github.com/glynskyi/notus-format

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  meta: ^1.3.0
  quill_format: ^1.0.0
  quiver_hashcode: ^3.0.0+1

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.4
  coverage: ^1.0.2