name: Dart CI

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:2.12

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: pub get

      - name: Analyze
        run: dartanalyzer --fatal-infos --fatal-warnings ./lib

      - name: Format code
        run: dart format -o none --set-exit-if-changed ./lib

      - name: Active coverage
        run: pub global activate coverage

      - name: Run tests
        run: dart test --coverage=coverage && pub run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --packages=.packages --report-on=lib

      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          path: coverage/lcov.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}